log:
  level: info
  format: json
  output: stdout

server:
  host: 0.0.0.0
  port: "8080"

generator:
  templates_dir: ./base/base
  rules_dir: ./base/rules
  rule_files:
    - path: DivineEngine/Surge/Ruleset/Unbreak.list
      policy: DIRECT
    - path: ACL4SSR/Clash/ProxyMedia.list
      policy: "🚀 节点选择"

subscription:
  extra_links: []

